#!/bin/bash
total 20 -rwxr--r-- 1 root root 18 Apr 13 13:08 0-current_working_directory -rwxr--r-- 1 root root 59 Apr 13 12:52 1-listit -rwxr--r-- 1 root root 18 Apr 13 13:32 2-bring_me_home -rw-r--r-- 1 root root 12 Apr 13 13:37 3-listfiles -rw-r--r-- 1 root root 4 Apr 13 10:26 README.md
